name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm install

    - name: Ensure Cypress has correct permissions
      run: |
        chmod +x ./node_modules/.bin/cypress
        chmod -R 777 ./node_modules

    - name: Run Cypress tests
      run: |
        npx cypress run
